version: '3.8'
services:
  spring-app:
    image: sha256:3baf0cfb3c15dce3e216c14c0c06edbce08088d4e5477723ca1c4ab147b96b79
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: springappdb
    ports:
      - "3307:3306"